#!/bin/bash

help() {
  echo "Usage:"
  echo "  zvm create <name> [cpu] [memory] [disk] [image]"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local name=$1
  local cpu=$2
  local memory=$3
  local disk=$4
  local image=$5

  if [ -z "$name" ]; then
    log::error "[$(timestamp)] name is required"
    exit 1
  fi

  if [ -z "$cpu" ]; then
    os::inquirer cpu "text" "how many cpu cores you want to share" true 2
  fi

  if [ -z "$memory" ]; then
    os::inquirer memory "text" "how many memory(unit: GB) you want to share" true 4
  fi

  if [ -z "$disk" ]; then
    os::inquirer disk "text" "how many disk(unit: GB) you want to share" true 10
  fi

  if [ -z "$image" ]; then
    local available_images=(
      "ubuntu:22.04"
      "ubuntu:20.04"
      "ubuntu:18.04"
      "ubuntu:16.04"
      "podman"
      "minikube"
      "jellyfin"
    )
    os::inquirer image "select" available_images "which os you want to choose" true 10
  fi

  log::info "[$(timestamp)] starting vm: $name with image($image) ..."

  case $image in
  ubuntu:22.04)
    image=ubuntu
    ;;
  ubuntu:20.04)
    image=20.04
    ;;
  ubuntu:18.04)
    image=18.04
    ;;
  ubuntu:16.04)
    image=https://cdimage.ubuntu.com/ubuntu-core/16/stable/current/ubuntu-core-16-amd64.img.xz
    ;;
  podman)
    image=docker
    ;;
  esac
  log::debug "[$(timestamp)] cmd (multipass launch --cpus $cpu --mem ${memory}G --disk ${disk}G --name $name $image)"
  multipass launch --cpus $cpu --mem ${memory}G --disk ${disk}G --name $name $image
  if [ "$?" = "0" ]; then
    log::success "[$(timestamp)] succeed to start vm: $name ."
  else
    log::success "[$(timestamp)] failed to start vm: $name ."
  fi
}

run() {
  core $@
}

run $@
