#!/bin/bash

help() {
  echo "Usage:"
  echo "  zvm exec <name>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local name=$1
  if [ -z "$name" ]; then
    local instances=$(multipass list | grep "Running" | awk '{print $1}')
    if [ -z "$instances" ]; then
      log::error "[$(timestamp)] no vm instances available"
      exit 1
    fi

    local instancesInq=($instances)
    os::inquirer name "select" instancesInq  "select the instance which you want to exec" true
  fi

  log::info "[$(timestamp)] exec vm: $name ..."
  multipass shell $name
}

run() {
  core "$@"
}

run "$@"
