#!/bin/bash

name() {
  local version=$(plugin::get_version $PLUGIN_VM_NAME)
  echo "Virtual Machine Manager ($(color::success $version))"
}

description() {
  echo "VM is a tool for managing virtual machines, based on multipass and lima."
}

usage() {
  echo "Usage:"
  echo "  zmicro vm create <name>        - Create a new virtual machine"
  echo "  zmicro vm ls                   - List all virtual machines"
  echo "  zmicro vm start <name>         - Start a virtual machine"
  echo "  zmicro vm stop <name>          - Stop a virtual machine"
  echo "  zmicro vm restart <name>       - Restart a virtual machine"
  echo "  zmicro vm remove <name>        - Remove a virtual machine"
  echo "  zmicro vm exec <name>          - Connect shell to a virtual machine"
  echo "  zmicro vm inspect <name>       - Inspect a virtual machine"
  echo "  zmicro vm help                 - Show help"
}

example() {
  echo "Example:"
  echo "  zmicro vm start test01"
}

core() {
  name
  echo ""
  description
  echo ""
  usage
  echo ""
  example
}

run() {
  core $@
}

run $@
