#!/bin/bash

help() {
  echo "Usage:"
  echo "  zvm remove <name>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local name=$1
  if [ -z "$name" ]; then
    log::error "[$(timestamp)] name is required"
    exit 1
  fi

  log::info "[$(timestamp)] removing vm: $name ..."

  multipass delete $name && multipass purge
  
  if [ "$?" = "0" ]; then
    log::success "[$(timestamp)] succeed to remove vm: $name ."
  else
    log::success "[$(timestamp)] failed to remove vm: $name ."
  fi
}

run() {
  core $@
}

run $@
