#!/bin/bash

help() {
  echo "Usage:"
  echo "  zvm start <name>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local name=$1
  if [ -z "$name" ]; then
    log::error "[$(timestamp)] name is required"
    exit 1
  fi

  log::info "[$(timestamp)] starting vm: $name ..."
  multipass launch --cpus 2 --mem 2G --name $name ubuntu
  if [ "$?" = "0" ]; then
    log::success "[$(timestamp)] succeed to start vm: $name ."
  else
    log::success "[$(timestamp)] failed to start vm: $name ."
  fi
}

run() {
  core $@
}

run $@
