#!/bin/bash

help() {
  echo "Usage:"
  echo "  zvm stop <name>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local name=$1
  if [ -z "$name" ]; then
    local instances=$(multipass list | grep "Running" | awk '{print $1}')
    if [ -z "$instances" ]; then
      log::error "[$(timestamp)] no vm instances available"
      exit 1
    fi

    local instancesInq=($instances)
    os::inquirer name "select" instancesInq "select the instance which you want to stop" true
  fi

  log::info "[$(timestamp)] stopping vm: $name ..."
  multipass stop $name
  if [ "$?" = "0" ]; then
    log::success "[$(timestamp)] succeed to stop vm: $name ."
  else
    log::success "[$(timestamp)] failed to stop vm: $name ."
  fi
}

run() {
  core $@
}

run $@
