#!/bin/bash

help() {
  echo "Usage:"
  echo "  zvm stop <name>"
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  local name=$1
  if [ -z "$name" ]; then
    log::error "[$(timestamp)] name is required"
    exit 1
  fi

  log::info "[$(timestamp)] stopping vm: $name ..."
  multipass stop $name
  if [ "$?" = "0" ]; then
    log::success "[$(timestamp)] succeed to stop vm: $name ."
  else
    log::success "[$(timestamp)] failed to stop vm: $name ."
  fi
}

run() {
  core $@
}

run $@
